name: Deploy to AWS EC2 with Docker-Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to AWS EC2 via SSH and Execute Shell Script
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Add the SSH private key for secure connection
          echo "${SSH_PRIVATE_KEY}" > private_key.pem
          chmod 600 private_key.pem

          # SSH to EC2 and execute deployment shell script
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
            # Navigate to project folder
            

            # Pull the latest changes from the repository
            git pull origin main
            cd /home/ubuntu/Three_tier_blogging_website_deployment


            # Run the shell script for installation and deployment
            chmod +x shellscript.sh
            ./shellscript.sh
          EOF

      - name: Clean Up SSH Key
        run: rm -f private_key.pem
