name: CI with SonarQube (Azure VM) & Snyk

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install Dependencies (including TypeScript)
      - name: Install Dependencies
        run: |
          cd frontend
          npm install
          npm install --save-dev typescript@latest

      # ---- SonarQube Analysis ----
      - name: SonarQube Scan (Azure VM)
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=wonderlust
            -Dsonar.organization=mayaworld13
            -Dsonar.typescript.tsconfigPath=frontend/tsconfig.sonar.json

      # ---- Wait & Check Quality Gate ----
      - name: SonarQube Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@v1.1.0
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      # ---- Build Frontend Artifact ----
      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      # ---- Upload Artifact ----
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/build # Or frontend/dist depending on your framework
